version: '3.4'

services: 
  sicstokafka:
    image: sicstokafka:latest
    network_mode: host
    volumes:
      - /opt/ansto/sics-to-kafka/config:/config
    command: ["python", "launcher.py", "--base=/config/pln_base.json", "--loglevel=DEBUG"]

