# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UByte(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUByte(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UByte()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def UByteBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x66\x31\x34\x32", size_prefixed=size_prefixed)

    # UByte
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UByte
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def UByteStart(builder): builder.StartObject(1)
def UByteAddValue(builder, value): builder.PrependUint8Slot(0, value, 0)
def UByteEnd(builder): return builder.EndObject()
